### PR TITLE
Add more saml methods

### PR DESCRIPTION
**Pull request by TracyWR**
Added single Logout Service endpoint (sls) and slo endpoint,  /metadata/ endpoint for the metadata

### CODE REVIEW

**Review by busykoala — COMMENTED** [review]
I've started manual testing now. I noticed following things:
- When directly hitting `?acs` it will error
- For me `?sls` is still raising `SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding`.
- The parenthesis around `{'SAMLResponse': request.query_params.get('SAMLResponse')}` will probably create a set with a dict. I don't think that's what you are trying to do.
- It is not yet formatted with the tooling in place (isort, flake8, black).
- I had to install `itsdangerous` to run it.
- It is not yet rebased onto the current master.
- There is unused code (`medatada` method).

Other than that it looks good and is now also very close to the python-saml example implementation (in flask) which I think is probably a good thing.

**Comment by TracyWR** [comment]
> * When directly hitting `?acs` it will error
**>  I test in my machine, it works**
> * For me `?sls` is still raising `SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding`.
> * The parenthesis around `{'SAMLResponse': request.query_params.get('SAMLResponse')}` will probably create a set with a dict. I don't think that's what you are trying to do.
>  **It has error because the get_data is empty, I assign SAMLResponse, it works. and it is a dictionary.** 
image

> * It is not yet formatted with the tooling in place (isort, flake8, black).
**>  I format it using flake 8, have this: T:\Profiles\Users\TracyWu\Documents\GitLab\tracy_git\fastapi-opa\fastapi_opa\auth\auth_saml.py:74:9:  E731 do not assign a lambda expression, use a def, I think we should ignore it, or what is the better way to change it?**
> * I had to install `itsdangerous` to run it.
> :)
> * It is not yet rebased onto the current master.
**> I am not sure how to do this.**
> * There is unused code (`medatada` method).
**It has been deleted.**

**Review by busykoala — COMMENTED** [review]
Let's assume the `acs` and `sls` errors are because of misconfiguration on my side (which is definitely possible) and also the parenthesis are fine there for some reason.

I would still expect you to rebase, run all the linting/formatting (you can ignore the lambda one in my opinion, since it is pretty clear) and add the package `itsdangerous` as a saml extra.
Also the README has to be adapted telling the user to add the session middleware plus the package version need to be increased by a minor version.

**Comment by TracyWR** [comment]
> * or me `?sls` is still raising `SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding`.
> 
> * The parenthesis around `{'S`
Have changed sls, it should work now :)

**Pull request closed without merging**
